# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += "\
    meta-TySOM-M-MPFS250T_yocto_bsp:${LAYERDIR}/dynamic-layers/meta-TySOM-M-MPFS250T_yocto_bsp/recipes-*/*/*.bbappend \
    meta-TySOM-M-MPFS250T_yocto_bsp:${LAYERDIR}/dynamic-layers/meta-TySOM-M-MPFS250T_yocto_bsp/recipes-*/*/*/*.bbappend \
"
BBFILE_COLLECTIONS += "meta_TySOM-M-MPFS250T_yocto_bsp"
BBFILE_PATTERN_meta_TySOM-M-MPFS250T_yocto_bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta_TySOM-M-MPFS250T_yocto_bsp = "6"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-polarfire-soc-bsp = "1"

LAYERDEPENDS_meta-polarfire-soc-bsp = "core"
LAYERDEPENDS_meta-polarfire-soc-bsp += "openembedded-layer"

LAYERSERIES_COMPAT_meta-polarfire-soc-bsp = "honister kirkstone"
